### ISSUE TITLE
Examples are wrong

### ISSUE THREAD

**Issue by Gansgar** [glium/glium#1799]
The examples are currently returning from the function if an event was received, there's no handler for. This results in the renderer braking, as long as you move your mouse.

**Comment by est31** [comment]
Can you say which examples have the problem?

**Comment by est31** [comment]
Oh you mean braking not breaking. As in: not rendering the current frame... Yeah this is a bug.

**Comment by InnocentusLime** [comment]
I think you have misread the code. The code renders only when it receives the `glutin::event::StartCause::ResumeTimeReached` or `glutin::event::StartCause::Init` event. (E.G. see `tutorial-13.rs` line 83).
So, I think it doesn't contain any kind of bug.

**Comment by est31** [comment]
@InnocentusLime this isn't fired when the mouse is being moved.

**Comment by InnocentusLime** [comment]
Yeah, that indeed happens... `tutorial5` showed it nicely... Maybe that is because the code "sleeps" after every event and ends up "spammed" other events like mouse movement?
I managed the triangle stop by producing lots of keyboard events.

**Comment by tadejpetric** [comment]
The issue was that the timer kept getting set every iteration and you only want to update it when the iteration was finished successfully. I think. 
(I don't wanna litter but if there's anything I should've done differently, both code and git wise please tell as it's my first pull request without browser editor)
