### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [glium/glium#1805]
An old version of `glium` has dependencies specified with `"*"` version requirement (`clock_ticks = "*"`, `khronos_api = "*"`, `glium_macros = "*"`, `obj = "*"`, etc.).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `glium` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.1
```

**Comment by est31** [comment]
My view is that this is a bug, and buggy crates.io versions shouldn't be yanked just for being buggy otherwise you'd yank all old versions.

Using `*` together with the `minimal-versions` feature isn't going to work in any way. Also, while I'd love to see the `minimal-versions` feature to become stable, unfortunately the cargo team decided to phase it out. It doesn't have a future.

Thus it's my view that we shouldn't do this. That being said, if you see any dependency requirement in current master or the last release that doesn't work with `minimal-versions`, please file a bug or a PR.

**Comment by est31** [comment]
Although we *should* probably remove the `glium = "*"` from readme...

**Comment by kornelski** [comment]
I'm filing bugs with crates partly to save the `minimal-versions` feature, and eliminating potential breakage from `"*"` was the first step.
