### ISSUE TITLE
release 0.28

### ISSUE THREAD

**Issue by aentity** [glium/glium#1876]
Release 0.28, new winit 0.23

**Comment by est31** [comment]
#1874 should have done the 0.28 release, but sadly the crates.io token used for publishing glium releases doesn't work any more, because recently crates.io has made all old tokens invalid because of a security issue with token generation.

I've contacted @tomaka (the only person who can set up such a token) via e mail and discord but haven't gotten a response since.

**Comment by est31** [comment]
#1877 succeeded, and 0.28 is out. Thanks everyone.
