### ISSUE TITLE
No way to share PixelBuffer and Texture between threads?

### ISSUE THREAD

**Issue by lucaszanella** [glium/glium#1880]
I'm writing a video player using glium and glutin. Currently it's working, however I'm getting bad performance. I suspect it's because I'm writing to the pixel buffers from the glutin window event pool, instead of from another thread. I'm doing that because I see no way of calling any of the pixel buffer or texture operations outside of the rendering thread.

Currently, I'm doing like this:

rendering thread:

```
glutin event loop {
    //receive decoded frame
    //create textures and pixel buffers with size of decoded frame if they're not already created
    //fill pixel buffer
    textures.raw_upload_from_pixel_buffer(...);
    //create uniforms from textures 
    target.draw(vertex_buffer, index_buffer, program, uniforms, Default::default());
}
```

frame thread:

```
loop {
    //receive decoded frame
    //send to rendering thread
}
```

I'd like to, at least, fill the pixel buffer from the frame thread. Also, does `textures.raw_upload_from_pixel_buffer` make a big copy? I see it accesses the pixel buffer slice. So what for is the pixel buffer used then? It seems that I'm copying 2 times.

I see no way of filling a texture or pixel buffer from the frame thread, because both `Texture2D` and `PixelBuffer` are not `Send + Sync`. 

Currently, I'm filling this from the glutin event loop. Why? Well:

`target.draw` needs `uniforms`, which needs the textures, so the textures must stay in the glutin event loop. Also textures need PixelBuffer, so the pixel buffers also must stay in the glutin even loop.

I'm getting a slow FPS and also the fps gets better when I make the window smaller. Anyone has idea why? The size of the window shouldn't matter for the PixelBuffer write calls I'm making, they should take the same time.

**Comment by est31** [comment]
Regarding the thread questions, OpenGL is single threaded. In order to use multiple threads, use [vulkano](https://github.com/vulkano-rs/vulkano) or another vulkan wrapper.

`raw_upload_from_pixel_buffer` doesn't do a copy IIRC, and if so, only internally in the GPUs memory.

As for the speed, it's possible that copying each pixel line one by one with a separate gpu call might be slower than, say, copying the smaller frame to ram first and then copying it to the gpu in one go. IIRC GPUs don't like being spammed with operations, but you need to benchmark that. Also maybe it's faster to copy the entire uncropped frame to a texture and then render it partially.

**Comment by lucaszanella** [comment]
I'm not copying per line as for this specific color format, ffmpeg provides line stride = width, so I'm copying the buffer at once just to test. I have the same example on C++ with GTK and OpenGL, and on there I always copy line by line, and it works very fast. On both examples I'm not rendering partially, I render after the pixel buffer is filled completely.

The fact that making the screen small makes the fps go up is also strange.
