### ISSUE TITLE
cannt work on windows arm 64

### ISSUE THREAD

**Issue by OElabs-official** [glium/glium#1964]
tested  toturial-01, works on host (win 10 x64 lstc (cargo run tested Ok),but force closed on target "cargo build --release --target=aarch64-pc-windows-msvc" >>
thread 'main' panicked at 'called Result::unwrap() on an Err value: GlutinCreationError(NoAvailablePixelFormat)', src\main.rs:8:60
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by Melchizedek6809** [comment]
You might need to install the OpenCL / OpenGL compatiblity pack: https://devblogs.microsoft.com/directx/announcing-the-opencl-and-opengl-compatibility-pack-for-windows-10-on-arm/ since afaik by default OpenGL support is quite limited on Windows/arm64.

I've got it installed on my Win11 ARM64 machine and most examples run just fine.
